FROM ubuntu:latest AS vim_ycm_base

SHELL ["/bin/bash", "-c"]

# Install essential packages and dependencies
RUN apt update -y && apt install -y \
    make \
    cmake \
    git \
    tree \
    software-properties-common \
    python3-dev \
    && add-apt-repository ppa:jonathonf/vim -y \
    && apt install vim -y \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir /root/.ssh/ \
    && mkdir /root/code/ \
    && ssh-keyscan github.com >>~/.ssh/known_hosts \
    && git clone https://github.com/jweeeezy/configs.git ~/configs \
    && make download -C ~/configs \
    && mkdir -p ~/.vim/bundle \
    && git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim \
    && vim +PluginInstall +qall

