FROM vim_ycm_base AS vim_ycm_clang

SHELL ["/bin/bash", "-c"]

# Installs clang and clangd for YCM autocompletion and syntax highlighting
RUN apt install -y \
    clang \
    clangd \
    llvm \
    && cd ~/.vim/plugged/YouCompleteMe/ && git submodule update --init --recursive \
    && python3 ~/.vim/plugged/YouCompleteMe/install.py --clangd-completer --system-libclang --force-sudo

# Adds clang.vim config to .vimrc
RUN echo "source ~/configs/vim_scripts/clang.vim" >> ~/.vimrc

