FROM ubuntu:latest

RUN apt update -y && apt upgrade -y
RUN apt install make -y
RUN apt install cmake -y
RUN apt install git -y
RUN apt install tree -y

RUN mkdir /root/.ssh/
RUN ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
RUN git clone https://github.com/jweeeezy/configs.git ~/configs

RUN apt install software-properties-common -y
RUN add-apt-repository ppa:jonathonf/vim -y
RUN apt install vim -y

RUN mkdir -p ~/.vim/bundle
RUN git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

RUN cd ~/configs && git checkout prod && make download
RUN vim +PluginInstall +qall

# Here I would have to separate what to implement onto the system
